service: tw-lambda-bot

provider:
  name: aws
  runtime: nodejs20.x

functions:
  signalProcessor:
    handler: dist/index.handler
    timeout: 300 # Set timeout to 300 seconds (5 minutes)
    events:
      - http:
          path: process-signal
          method: post

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - '!node_modules/aws-sdk/**'
